### ISSUE TITLE
PlatformException(error, Unknown URI: content://downloads/public_downloads/....

### ISSUE THREAD

**Issue by JeanChristopheMobizel** [KasemJaffer/flutter_absolute_path#6]
When i try 
```
var path = await FlutterAbsolutePath.getAbsolutePath("content://com.android.providers.downloads.documents/document/3661);
```
I get this exception 

Failed to handle method call
java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3661
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1460)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1297)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1017)
	at com.kasem.flutter_absolute_path.FileDirectory.getDataColumn(FileDirectory.kt:91)
	at com.kasem.flutter_absolute_path.FileDirectory.getAbsolutePath(FileDirectory.kt:49)
	at com.kasem.flutter_absolute_path.FlutterAbsolutePathPlugin.onMethodCall(FlutterAbsolutePathPlugin.kt:42)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:376)
	at android.os.Looper.loop(Looper.java:244)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
 	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

exception opening file : PlatformException(error, Unknown URI: content://downloads/public_downloads/3661, null, java.lang.IllegalArgumentException: Unknown URI: content
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1460)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1297)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1017)
	at com.kasem.flutter_absolute_path.FileDirectory.getDataColumn(FileDirectory.kt:91)
	at com.kasem.flutter_absolute_path.FileDirectory.getAbsolutePath(FileDirectory.kt:49)
	at com.kasem.flutter_absolute_path.FlutterAbsolutePathPlugin.onMethodCall(FlutterAbsolutePathPlugin.kt:42)

**Comment by Mike-3** [comment]
I have the same problem.
